server:
  port: 8082

spring:
  application:
    name: sports-auth
  config:
    import: "optional:nacos:common-config.yml,optional:nacos:sports-auth.yml"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.32:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
        weight: 1
      config:
        server-addr: 192.168.31.32:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml

knife4j:
  enable: true
  setting:
    language: zh_cn
