server:
  port: 8079

spring:
  application:
    name: sports-gateway
  # 导入 Nacos 配置：网关只需要自己的专属配置
  config:
    import: "optional:nacos:sports-gateway.yml"
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.32:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 192.168.31.32:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false